Repository akeneo/pim-helpcenter, pull requests merged in 2020-01, with the labels that each got.

#428 Add paragraph on suggested mapping
  content/md/franklin-insights/franklin-insights-mappings.md
Labels: 4.0, needs_review

#430 New article to understand data quality feature
  content/md/what-is/understand-data-quality.md
Labels: 4.0, needs_review

#432 Improve data quality
  content/md/products-super-power/improve-data-quality.md
Labels: 4.0, needs_review

#429 Created a new article for Quality Highlights and Franklin key figures
  content/md/franklin-insights/franklin-insights-subscriptions.md
  content/md/franklin-insights/franklin-key-figures.md
Labels: 4.0

#427 Article about the Connection dashboard
  content/md/connectivity/connection-dashboard.md
  content/md/connectivity/img/source-connection-dropdown.png
Labels: 4.0, needs_review

#423 Finalise the connection settings part of the doc
  content/md/connectivity/how-to-connect-my-pim.md
  content/md/connectivity/img/connection-image-choice.png
  content/md/connectivity/img/connections-overview.png
  content/md/connectivity/img/copy-paste-credentials.png
  content/md/connectivity/img/credentials-in-connection-form.png
  content/md/connectivity/img/delete-a-connection.png
  content/md/connectivity/img/password-showed-only-once.png
  content/md/connectivity/img/regenerate-icon-button.png
  content/md/connectivity/img/regenerate-password-icon-button.png
  content/md/connectivity/manage-your-connections.md
  content/md/what-is/img/connections-screen.png
  content/md/what-is/img/pim-with-many-connections.png
  content/md/what-is/what-is-a-connection.md
Labels: 4.0, needs_review

#434 Remove since mentions
  content/md/first-steps/login.md
  content/md/first-steps/manage-reference-entities.md
  content/md/franklin-insights/franklin-insights-mappings.md
  content/md/franklin-insights/franklin-insights-subscriptions.md
  content/md/productivity/proposals-workflow.md
  content/md/products-super-power/enrich-your-reference-entity-records.md
  content/md/products-super-power/product-mass-actions.md
  content/md/products-super-power/work-on-a-product.md
  content/md/what-is/what-is-an-attribute.md
Labels: 4.0, needs_review

#441 Add section about permissions
  content/md/connectivity/manage-your-connections.md
  content/md/permissions-settings/manage-the-interface-and-actions-accesses.md
  content/md/permissions-settings/manage-the-web-api-permissions.md
  content/md/permissions-settings/what-is-a-role.md
Labels: 4.0, needs_review

#447 Added assets + entities
  content/md/administration/catalog-volume-monitoring.md
Labels: 4.0, needs_review

#431 update articles link between assets & products
  content/md/first-steps/manage-your-attributes.md
  content/md/products-super-power/work-on-a-product.md
  content/md/what-is/what-is-an-attribute.md
Labels: 4.0, to_be_merged

#444 deleted old assets articles
  content/md/assets/assets-transformation.md
  content/md/assets/upload-assets.md
  content/md/assets/work-with-assets.md
  content/md/permissions-settings/access-rights-on-assets.md
  content/md/what-is/what-is-an-asset.md
Labels: 4.0, to_be_merged

#446 Access rights on asset manager
  content/md/permissions-settings/access-rights-on-asset-families.md
Labels: 4.0, needs_review

#433 New enrich your assets
  content/md/products-super-power/enrich-your-assets.md
Labels: 4.0, needs_review

#435 New manage asset families
  content/md/first-steps/manage-asset-families.md
Labels: 4.0, needs_review

#438 About asset transformations
  content/md/assets/assets-transformation.md
Labels: 4.0, needs_review

#436 New what about assets
  content/md/what-is/img/asset-manager.svg
  content/md/what-is/what-about-assets.md
Labels: 4.0, needs_review

#445 New acl asset manager
  content/md/permissions-settings/manage-the-interface-and-actions-accesses.md
Labels: 4.0, needs_review

#437 added about product link rules article
  content/md/assets/about-product-link-rules.md
Labels: 4.0, needs_review

#448 New create and display assets
  content/md/assets/create-and-display-assets.md
Labels: 4.0

#449 From pam to new am
  content/md/assets/from-PAM-to-new-AM.md
Labels: 4.0, needs_review

#439 differences between PAM & AM
  content/md/assets/differences-PAM-AM.md
Labels: 4.0

#459 update asset categories
  content/md/assets/from-PAM-to-new-AM.md
Labels: 4.0, needs_review

#462 Add screenshots and change QH title
  content/md/franklin-insights/franklin-insights-mappings.md
  content/md/franklin-insights/franklin-key-figures.md
  content/md/franklin-insights/img/franklin_suggested_mapping01.png
  content/md/franklin-insights/img/franklin_suggested_mapping02.png
  content/md/products-super-power/img/data-quality-charts.png
  content/md/products-super-power/img/data-quality-dashboard.png
  content/md/products-super-power/img/data-quality-panel.png
  content/md/products-super-power/img/data-quality-pef.png
  content/md/products-super-power/img/data-quality-spelling.png
  content/md/products-super-power/img/data-quality-title-formatting.png
  content/md/products-super-power/img/data-quality-widgets.png
  content/md/products-super-power/improve-data-quality.md
  content/md/what-is/img/data-quality-dashboard.jpg
  content/md/what-is/img/data-quality-grid.png
  content/md/what-is/img/data-quality-panel.png
  content/md/what-is/img/data-quality-pef.png
  content/md/what-is/understand-data-quality.md
Labels: 4.0, needs_review

#461 Assets screenshots on product
  content/md/products-super-power/img/asset-picker.png
  content/md/products-super-power/img/asset_collection_attribute.png
  content/md/products-super-power/img/basket.png
  content/md/products-super-power/img/preview.jpg
  content/md/products-super-power/img/preview.png
  content/md/products-super-power/img/sort_in_asset_collection.png
  content/md/products-super-power/work-on-a-product.md
Labels: 4.0, needs_review

#465 Screenshots asset transfo
  content/md/assets/assets-transformation.md
  content/md/assets/img/Assetes_ImportAfterUpload.png
  content/md/assets/img/Assets_Transformations.png
  content/md/assets/img/Assets_TransformationsFormat.png
Labels: 4.0, needs_review
