Repository akeneo/pim-helpcenter, pull requests merged in 2020-02, with the labels that each got.

#463 Screenshots enrich assets
  content/md/products-super-power/img/Assets_Completeness.png
  content/md/products-super-power/img/Assets_DeleteAllAssets.png
  content/md/products-super-power/img/Assets_Deletion.png
  content/md/products-super-power/img/Assets_DisplayAllProducts.png
  content/md/products-super-power/img/Assets_DisplayProducts.png
  content/md/products-super-power/img/Assets_LocaleSwitcher.png
  content/md/products-super-power/img/drag_drop.jpg
  content/md/products-super-power/work-on-your-assets.md
Labels: 4.0, needs_review

#469 changed the themes
  content/md/assets/about-product-link-rules.md
Labels: 4.0, needs_review

#470 removed channels asset transformations part (old PAM)
  content/md/first-steps/manage-channels.md
Labels: 4.0, needs_review

#471 Changed screenshot + updated example
  content/md/permissions-settings/access-rights-on-asset-families.md
  content/md/permissions-settings/img/Assets_FamilyPermissions.png
Labels: 4.0, needs_review

#472 Updates create and display assets
  content/md/assets/create-and-display-assets.md
  content/md/assets/img/Assets_FilterOptions.png
  content/md/assets/img/Assets_Library.png
  content/md/assets/img/Assets_MassUploadList.png
  content/md/assets/img/Assets_Search1Word.png
  content/md/assets/img/Assets_Search2Words.png
  content/md/assets/img/Assets_UnitaryCreation.png
  content/md/assets/img/Assets_UploadAssets.png
  content/md/assets/img/Assets_UploadLocalizableAndScopableAssets.png
  content/md/assets/img/Assets_UploadLocalizableAssets.png
  content/md/assets/img/Assets_UploadScopableAssets.png
Labels: 4.0, needs_review

#468 Updates manage asset families
  content/md/first-steps/img/Assets_AddAttributes.png
  content/md/first-steps/img/Assets_AddOptions.png
  content/md/first-steps/img/Assets_AssetFamilyProperties.png
  content/md/first-steps/img/Assets_AttributeCompleteness.png
  content/md/first-steps/img/Assets_Attributes.png
  content/md/first-steps/img/Assets_AttributesLocaleSwitcher.png
  content/md/first-steps/img/Assets_FamilyDeletion.png
  content/md/first-steps/img/Assets_LibraryCreateFamily.png
  content/md/first-steps/img/Assets_ManageOptions.png
  content/md/first-steps/img/Assets_TranslateOptions.png
  content/md/first-steps/img/Assets_YoutubeLink.png
  content/md/first-steps/manage-asset-families.md
Labels: 4.0, needs_review

#473 Upload new assets from the pef
  content/md/products-super-power/img/Assets_AssetCollectionAttribute.png
  content/md/products-super-power/img/Assets_AssetPicker.png
  content/md/products-super-power/img/Assets_Preview.png
  content/md/products-super-power/img/Assets_SortInAssetCollection.png
  content/md/products-super-power/img/Assets_UploadFromPEF.png
  content/md/products-super-power/work-on-a-product.md
Labels: 4.0, needs_review

#474 Export new assets
  content/md/assets/export-assets.md
  content/md/assets/img/Assets_ExportAssets.png
  content/md/assets/img/Assets_ExportProfileSettings.png
  content/md/assets/img/Assets_ProcessTracker.png
Labels: 4.0, needs_review

#475 Updates what about assets
  content/md/what-is/img/Assets_Asset.png
  content/md/what-is/img/Assets_AssetFamilies.png
  content/md/what-is/img/Assets_AssetManager.svg
  content/md/what-is/img/Assets_ProductSheet.png
  content/md/what-is/what-about-assets.md
Labels: 4.0, needs_review

#466 Add screenshot and Modify Franklin key figures title
  content/md/franklin-insights/franklin-key-figures.md
  content/md/franklin-insights/img/Akeneo_Screenshot_Franklin_Insights_key-figures.png
Labels: 4.0, needs_review

#464 Removed "asset value extrapolation" + added screenshots
  content/md/assets/about-product-link-rules.md
  content/md/assets/img/Assets_NamingConvention.png
  content/md/assets/img/Assets_ProductLinkRules.png
Labels: 4.0, needs_review

#476 Updates from pam to am
  content/md/assets/from-PAM-to-new-AM.md
Labels: 4.0, needs_review

#492 Fixed the warning about product model
  content/md/assets/about-product-link-rules.md
Labels: needs_review

#490 added the optimize-jpeg operation
  content/md/assets/assets-transformation.md
Labels: needs_review

#484 Warning explanation about the connection username
  content/md/connectivity/manage-your-connections.md
Labels: Serenity

#491 Update asset edit form
  content/md/products-super-power/img/Assets_AssetCompleteness.png
  content/md/products-super-power/img/Assets_AssetEditForm.png
  content/md/products-super-power/img/Assets_AssetForm.png
  content/md/products-super-power/img/Assets_Completeness.png
  content/md/products-super-power/img/Assets_Deletion.png
  content/md/products-super-power/img/Assets_DisplayAllProducts.png
  content/md/products-super-power/img/Assets_DisplayProductsMessage.png
  content/md/products-super-power/img/Assets_LinkedProducts.png
  content/md/products-super-power/img/Assets_LocaleSwitcher.png
  content/md/products-super-power/work-on-your-assets.md
  content/md/what-is/img/Assets_Asset.png
  content/md/what-is/img/Assets_AssetEditForm.png
  content/md/what-is/what-about-assets.md
Labels: needs_review
